language: python
sudo: required

services:
  - docker

python:
  - 3.6

env:
  - DJANGO=2.1.2

install:
  - pip3 install -r requirements.txt
  - pip3 install coveralls

before_script:
  - docker pull coderdude/ase1:v1
  - docker tag coderdude/ase1:v1 pybuntu
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - python manage.py check
  - coverage run --source=main_page,questions,registration manage.py test

after_success:
  coveralls

notifications:
  email:
    recipients:
      - coderdude1999@gmail.com
    on_success: change
    on_failure: always
